# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-20 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='president',
            name='motto',
            field=models.TextField(default=''),
        ),
    ]
