# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-22 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presidents', '0002_president_motto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstLady',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_ladies', to='presidents.President')),
            ],
        ),
    ]
