# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-22 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0002_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroPower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='heropower',
            name='power',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heros', to='superheroes.Power'),
        ),
        migrations.AddField(
            model_name='heropower',
            name='superHero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powers', to='superheroes.SuperHero'),
        ),
    ]
